/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AdvertiserFinancial;

import Business.EcoSystem;
import Business.Enterprise.AdvertiserEnterprise;
import Business.Organization.AdvertiserFinancialOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Neethan
 */
public class AdvertiserFinancialWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AdvertiserFinancialOrganization organization;
    private AdvertiserEnterprise enterprise;
    private EcoSystem system;
    /**
     * Creates new form AdvertiserFinancialWorkAreaJPanel
     */
    public AdvertiserFinancialWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, AdvertiserFinancialOrganization organization, AdvertiserEnterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise =enterprise;
        this.organization = organization;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        manageBalance = new javax.swing.JButton();
        manageAdpay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        manageBalance1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(570, 440));
        setPreferredSize(new java.awt.Dimension(570, 440));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("- Advertiser Financial Specialist");

        manageBalance.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageBalance.setText("Check Enterprise Balance");
        manageBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBalanceActionPerformed(evt);
            }
        });

        manageAdpay.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageAdpay.setText("Manage Ads Payment");
        manageAdpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdpayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area ");

        manageBalance1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageBalance1.setText("Check Enterprise Invoice");
        manageBalance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBalance1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(manageAdpay, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(manageAdpay, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBalanceActionPerformed
        // TODO add your handling code here:
        AdvertiserCheckBalanceJPanel adcbjp = new AdvertiserCheckBalanceJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("AdvertiserCheckBalanceJPanel" , adcbjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageBalanceActionPerformed

    private void manageAdpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdpayActionPerformed
        // TODO add your handling code here:
        AdvertiserManageAdJPanel amadjp = new AdvertiserManageAdJPanel(userProcessContainer,userAccount, organization,enterprise,system);
        userProcessContainer.add("AdvertiserManageAdJPanel",amadjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAdpayActionPerformed

    private void manageBalance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBalance1ActionPerformed
        // TODO add your handling code here:
        CheckInvoiceJPanel cinjp = new CheckInvoiceJPanel(userProcessContainer,userAccount, organization,enterprise,system);
        userProcessContainer.add("CheckInvoiceJPanel", cinjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageBalance1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageAdpay;
    private javax.swing.JButton manageBalance;
    private javax.swing.JButton manageBalance1;
    // End of variables declaration//GEN-END:variables
}
