/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SSPMarketing;

import Business.Enterprise.SSPEnterprise;
import Business.Organization.Organization;
import Business.Organization.SSPFinancialOrganization;
import Business.Organization.SSPMarketingOrganization;
import Business.Space.Space;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AssignSpaceWorkRequest;
import Business.WorkQueue.SpacePayWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neethan
 */
public class ManageSpaceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SSPMarketingOrganization organization;
    private SSPEnterprise enterprise;
    
    /**
     * Creates new form ManageSpaceJPanel
     */
    public ManageSpaceJPanel(JPanel userProcessContainer, UserAccount userAccount, SSPMarketingOrganization organization, SSPEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = organization;
        populateTable();
    }

    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)spaceList.getModel();
        dtm.setRowCount(0);
        
        if(organization.getWorkQueue().getWorkRequestList()==null){
            organization.getWorkQueue().setWorkRequestList(new ArrayList());
        }
        for(WorkRequest wq : organization.getWorkQueue().getWorkRequestList()){
            if(wq instanceof AssignSpaceWorkRequest){
                Object[] row = new Object[2];
                row[0] = (AssignSpaceWorkRequest)wq;
                row[1] = ((AssignSpaceWorkRequest)wq).getSpaceOwner();
                dtm.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        spaceList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        alert = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(570, 440));
        setPreferredSize(new java.awt.Dimension(570, 440));

        spaceList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Space Name", "Publisher"
            }
        ));
        jScrollPane1.setViewportView(spaceList);

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Approve Space");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        alert.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(alert)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(alert)
                .addGap(114, 114, 114)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = spaceList.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a space from the list first.");
            return;
        }

        AssignSpaceWorkRequest asswq = (AssignSpaceWorkRequest)spaceList.getValueAt(selectedRow, 0);
        Space s = asswq.getSpace();

        int selectedValue = JOptionPane.showConfirmDialog(null, "You sure you want to assign this space?", "Warnning", JOptionPane.YES_NO_OPTION);
        if(selectedValue == JOptionPane.YES_OPTION){
            enterprise.getSpaceList().getSpaceList().add(s);
            asswq.setReceiver(userAccount);
            asswq.setStatus("Assigned");
            s.setStatus("Assigned");
            s.setSaler(enterprise);
            organization.getWorkQueue().getWorkRequestList().remove(asswq);
            SpacePayWorkRequest spwr = new SpacePayWorkRequest(s);
            spwr.setSender(userAccount);
            spwr.setPayEn(enterprise);
            spwr.setStatus("Assigned");
            userAccount.getWorkQueue().getWorkRequestList().add(spwr);
            organization.getWorkQueue().getWorkRequestList().add(spwr);
            for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
                if(o instanceof SSPFinancialOrganization){
                    o.getWorkQueue().getWorkRequestList().add(spwr);
                }
            }
            alert.setText("Space Approved Sucessfully!");
            populateTable();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable spaceList;
    // End of variables declaration//GEN-END:variables
}
