/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SSPMarketing;

import Business.EcoSystem;
import Business.Enterprise.SSPEnterprise;
import Business.Organization.SSPMarketingOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Neethan
 */
public class SSPMarketWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SSPEnterprise enterprise;
    private SSPMarketingOrganization organization;
    private EcoSystem system;
    /**
     * Creates new form SSPMarketWorkAreaJPanel
     */
    public SSPMarketWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount, SSPMarketingOrganization organization, SSPEnterprise enterprise, EcoSystem system ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.system = system;
        this.organization = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        manageAdsJButton = new javax.swing.JButton();
        manageAdsJButton1 = new javax.swing.JButton();
        manageAdsJButton2 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(570, 440));
        setPreferredSize(new java.awt.Dimension(570, 440));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("- SSP Marketing Specialist");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area ");

        manageAdsJButton.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageAdsJButton.setText("Manage DSP Coop Request");
        manageAdsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdsJButtonActionPerformed(evt);
            }
        });

        manageAdsJButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageAdsJButton1.setText("Manage Publisher Space Assign");
        manageAdsJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdsJButton1ActionPerformed(evt);
            }
        });

        manageAdsJButton2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageAdsJButton2.setText("Check Assigned Space & DSP");
        manageAdsJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdsJButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(manageAdsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageAdsJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(manageAdsJButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(manageAdsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageAdsJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageAdsJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAdsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdsJButtonActionPerformed
        // TODO add your handling code here:
        ManageCoopJPanel mcpjp = new ManageCoopJPanel(userProcessContainer,userAccount,enterprise,organization,system);
        userProcessContainer.add("ManageCoopJPanel",mcpjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
     
    }//GEN-LAST:event_manageAdsJButtonActionPerformed

    private void manageAdsJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdsJButton1ActionPerformed
        // TODO add your handling code here:
        ManageSpaceJPanel mspjp = new ManageSpaceJPanel(userProcessContainer, userAccount,organization,enterprise);
        userProcessContainer.add("ManageSpaceJPanel",mspjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageAdsJButton1ActionPerformed

    private void manageAdsJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdsJButton2ActionPerformed
        // TODO add your handling code here:
        CheckSpaceDSPJPanel csdsjp = new CheckSpaceDSPJPanel(userProcessContainer,userAccount,enterprise,organization,system);
        userProcessContainer.add("CheckSpaceDSPJPanel", csdsjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAdsJButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageAdsJButton;
    private javax.swing.JButton manageAdsJButton1;
    private javax.swing.JButton manageAdsJButton2;
    // End of variables declaration//GEN-END:variables
}
