/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SSPFinancial;

import Business.EcoSystem;
import Business.Enterprise.SSPEnterprise;
import Business.Financial.FinancialAccount;
import Business.Organization.Organization;
import Business.Organization.PublisherFinancialOrganization;
import Business.Organization.SSPFinancialOrganization;
import Business.Organization.SSPMarketingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SpacePayWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neethan
 */
public class MakeSpacePaymentJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SSPEnterprise enterprise;
    private SSPFinancialOrganization organization;
    private EcoSystem system;
    /**
     * Creates new form MakeSpacePaymentJPanel
     */
    public MakeSpacePaymentJPanel(JPanel userProcessContainer, UserAccount userAccount,SSPEnterprise enterprise,SSPFinancialOrganization organization,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = organization;
        this.system = system;
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)paymentList.getModel();
        dtm.setRowCount(0);
        if(organization.getWorkQueue().getWorkRequestList()== null){
            organization.getWorkQueue().setWorkRequestList(new ArrayList());
        }
        for(WorkRequest wq : organization.getWorkQueue().getWorkRequestList()){
            if(wq instanceof SpacePayWorkRequest){
                if(((SpacePayWorkRequest)wq).getStatus().equals("Assigned")){
                    Object[] row = new Object[3];
                    row[0] = (SpacePayWorkRequest)wq;
                    row[1] = ((SpacePayWorkRequest)wq).getSpace().getOwner();
                    row[2] = ((SpacePayWorkRequest)wq).getSpace().getPrice();
                    dtm.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        paymentList = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        alert = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(570, 440));

        paymentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Space", "Publisher", "Price"
            }
        ));
        jScrollPane1.setViewportView(paymentList);

        jButton3.setText("Make Payment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        alert.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alert)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(alert)
                .addGap(97, 97, 97)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = paymentList.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a space from the list first.");
            return;
        }
        
        SpacePayWorkRequest spwr = (SpacePayWorkRequest)paymentList.getValueAt(selectedRow, 0);
        
        int selectedValue = JOptionPane.showConfirmDialog(null, "You sure you want to make payment for this space?", "Warning", JOptionPane.YES_NO_OPTION);
        if(selectedValue == JOptionPane.YES_OPTION){
            spwr.setSender(userAccount);
            userAccount.getWorkQueue().getWorkRequestList().add(spwr);
            spwr.getSpace().setStatus("Paid");
            spwr.setStatus("Wait for confirm");
            for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
                if(o instanceof SSPMarketingOrganization){
                    o.getWorkQueue().getWorkRequestList().remove(spwr);
                    break;
                }
            }
            for(Organization oo : spwr.getSpace().getOwner().getOrganizationDirectory().getOrganizationList()){
                if(oo instanceof PublisherFinancialOrganization){
                    oo.getWorkQueue().getWorkRequestList().add(spwr);
                }
            }
            float minamount = spwr.getSpace().getPrice();
            if(enterprise.getFinancialAccount()==null){
                enterprise.setFinancialAccount(new FinancialAccount());
            }
            enterprise.getFinancialAccount().makePayment(minamount);
            alert.setText("Payment Made Sucessfully!");
            populateTable();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable paymentList;
    // End of variables declaration//GEN-END:variables
}
