/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SSPFinancial;

import Business.EcoSystem;
import Business.Enterprise.SSPEnterprise;
import Business.Organization.SSPFinancialOrganization;
import Business.Organization.SSPMarketingOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Neethan
 */
public class SSPFinancialWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SSPFinancialOrganization organization;
    private SSPEnterprise enterprise;
    private EcoSystem system;
    /**
     * Creates new form SSPFinancialWorkAreaJPanel
     */
    public SSPFinancialWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, SSPFinancialOrganization organization, SSPEnterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = organization;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        manageIncome = new javax.swing.JButton();
        manageBalance = new javax.swing.JButton();
        manageSpacePayment = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(570, 440));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("- SSP Financial Specialist");

        manageIncome.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageIncome.setText("Manage New Income");
        manageIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageIncomeActionPerformed(evt);
            }
        });

        manageBalance.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageBalance.setText("Check Enterprise Balance");
        manageBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBalanceActionPerformed(evt);
            }
        });

        manageSpacePayment.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageSpacePayment.setText("Make Space Payment");
        manageSpacePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSpacePaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(manageIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageSpacePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(manageSpacePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageIncomeActionPerformed
        // TODO add your handling code here:
        SSPManageIncomeJPanel ssmijp = new SSPManageIncomeJPanel(userProcessContainer,userAccount, organization,enterprise,system);
        userProcessContainer.add("SSPManageIncomeJPanel" , ssmijp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageIncomeActionPerformed

    private void manageBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBalanceActionPerformed
        // TODO add your handling code here:
        SSPCheckBalanceJPanel scbjp = new SSPCheckBalanceJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("SSPCheckBalanceJPanel" , scbjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageBalanceActionPerformed

    private void manageSpacePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSpacePaymentActionPerformed
        // TODO add your handling code here:
        MakeSpacePaymentJPanel mspjp = new MakeSpacePaymentJPanel(userProcessContainer,userAccount, enterprise,organization,system);
        userProcessContainer.add("ManageRentJPanel", mspjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageSpacePaymentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageBalance;
    private javax.swing.JButton manageIncome;
    private javax.swing.JButton manageSpacePayment;
    // End of variables declaration//GEN-END:variables
}
