/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PublisherFinancial;

import Business.EcoSystem;
import Business.Enterprise.PublisherEnterprise;
import Business.Enterprise.SSPEnterprise;
import Business.Organization.Organization;
import Business.Organization.PublisherFinancialOrganization;
import Business.Organization.SSPFinancialOrganization;
import Business.Space.Space;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SpacePayAlertWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neethan
 */
public class ManageRentJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private PublisherFinancialOrganization organization;
    private PublisherEnterprise enterprise;
    private EcoSystem system;
    /**
     * Creates new form ManageRentJPanel
     */
    public ManageRentJPanel(JPanel userProcessContainer, UserAccount userAccount, PublisherFinancialOrganization organization, PublisherEnterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        populateTable();
    }

    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)spaceList.getModel();
        dtm.setRowCount(0);
        if(enterprise.getSpaceList().getSpaceList() == null){
            enterprise.getSpaceList().setSpaceList(new ArrayList());
        }
        for(Space s : enterprise.getSpaceList().getSpaceList()){
            Object[] row = new Object[4];
            row[0] = s;
            row[1] = s.getSaler();
            row[2] = s.getPrice();
            row[3] = s.getStatus();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        spaceList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        alert = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(570, 440));

        spaceList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Space", "SSP", "Rent", "Status"
            }
        ));
        jScrollPane1.setViewportView(spaceList);

        jButton1.setText("Sent Pay Alert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        alert.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(alert)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(alert)
                .addGap(62, 62, 62)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = spaceList.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a space from table first.");
            return;
        }
        
        String status = (String)spaceList.getValueAt(selectedRow, 3);
        if(status.equals("Paid") || status.equals("Confirm Receive")){
            JOptionPane.showMessageDialog(null, "The Space has already been paid, select another space.");
            return;
        }
        if(status.equals("Waiting Assignment")){
            JOptionPane.showMessageDialog(null, "Still waiting for approve, please wait.");
            return;
        }
        
        int selectedValue = JOptionPane.showConfirmDialog(null, "Are you sure you want to send a payment alert?", "Warning",JOptionPane.YES_NO_OPTION);
        if(selectedValue == JOptionPane.YES_OPTION){
            Space s = (Space) spaceList.getValueAt(selectedRow, 0);
            for(WorkRequest wq : organization.getWorkQueue().getWorkRequestList()){
                if(wq instanceof SpacePayAlertWorkRequest){
                    if(((SpacePayAlertWorkRequest)wq).getSpace().equals(s)){
                        JOptionPane.showMessageDialog(null, "This Space has already sent alert before, choose another one.");
                        return;
                    }
                }
            }
            SpacePayAlertWorkRequest spawq = new SpacePayAlertWorkRequest(s);
            SSPEnterprise ss = (SSPEnterprise)spaceList.getValueAt(selectedRow, 1);
            spawq.setSender(userAccount);
            spawq.setSpaceOwner(enterprise);
            spawq.setSpaceSaler(ss);
            userAccount.getWorkQueue().getWorkRequestList().add(spawq);
            organization.getWorkQueue().getWorkRequestList().add(spawq);
            for(Organization o : ss.getOrganizationDirectory().getOrganizationList()){
                if(o instanceof SSPFinancialOrganization){
                    ((SSPFinancialOrganization)o).getWorkQueue().getWorkRequestList().add(spawq);
                }
            }
            alert.setText("Pay Alert Send Sucessfully!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable spaceList;
    // End of variables declaration//GEN-END:variables
}
