/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PublisherFinancial;

import Business.EcoSystem;
import Business.Enterprise.PublisherEnterprise;
import Business.Organization.PublisherFinancialOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Neethan
 */
public class PublisherFinancialWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private PublisherFinancialOrganization organization;
    private PublisherEnterprise enterprise;
    private EcoSystem system;
    /**
     * Creates new form PublisherFinancialWorkAreaJPanel
     */
    public PublisherFinancialWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, PublisherFinancialOrganization organization, PublisherEnterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        manageRentJButton = new javax.swing.JButton();
        manageRentJButton1 = new javax.swing.JButton();
        manageRentJButton2 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(570, 440));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("- Publisher Financial Specialist");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area ");

        manageRentJButton.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageRentJButton.setText("Manage Rent Payment");
        manageRentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRentJButtonActionPerformed(evt);
            }
        });

        manageRentJButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageRentJButton1.setText("Check Enterprise Balance");
        manageRentJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRentJButton1ActionPerformed(evt);
            }
        });

        manageRentJButton2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        manageRentJButton2.setText("Manage New Income");
        manageRentJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRentJButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(manageRentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageRentJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageRentJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(manageRentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageRentJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageRentJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageRentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRentJButtonActionPerformed
        // TODO add your handling code here:
        ManageRentJPanel mrjp = new ManageRentJPanel(userProcessContainer,userAccount, organization,enterprise,system);
        userProcessContainer.add("ManageRentJPanel", mrjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageRentJButtonActionPerformed

    private void manageRentJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRentJButton1ActionPerformed
        // TODO add your handling code here:
        CheckBalanceJPanel cbjp = new CheckBalanceJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("CheckBalanceJPanel" , cbjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageRentJButton1ActionPerformed

    private void manageRentJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRentJButton2ActionPerformed
        // TODO add your handling code here:
        ManageIncomeJPanel mijp = new ManageIncomeJPanel(userProcessContainer,userAccount, organization,enterprise,system);
        userProcessContainer.add("ManageIncomeJPanel" , mijp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageRentJButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageRentJButton;
    private javax.swing.JButton manageRentJButton1;
    private javax.swing.JButton manageRentJButton2;
    // End of variables declaration//GEN-END:variables
}
