/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DSPFinancial;

import Business.EcoSystem;
import Business.Enterprise.DSPEnterprise;
import Business.Enterprise.SSPEnterprise;
import Business.Organization.AdvertiserFinancialOrganization;
import Business.Organization.DSPFinancialOrganization;
import Business.Organization.Organization;
import Business.Organization.SSPFinancialOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdPayWorkRequest;
import Business.WorkQueue.AdShowWorkRequest;
import Business.WorkQueue.ChargeAdvertiserWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neethan
 */
public class ManageAdPayJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private DSPFinancialOrganization organization;
    private DSPEnterprise enterprise;
    private EcoSystem system;
    /**
     * Creates new form ManageAdPayJPanel
     */
    public ManageAdPayJPanel(JPanel userProcessContainer, UserAccount userAccount, DSPFinancialOrganization organization, DSPEnterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount ;
        this.enterprise = enterprise;
        this.organization = organization;
        this.system = system;
        populateTable();
    }

    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)adpay.getModel();
        dtm.setRowCount(0);
        
        if(organization.getWorkQueue().getWorkRequestList()==null){
            organization.getWorkQueue().setWorkRequestList(new ArrayList());
        }
        for(WorkRequest wr : organization.getWorkQueue().getWorkRequestList()){
            if(wr instanceof AdShowWorkRequest){
                Object[] row = new Object[4];
                row[0] = (AdShowWorkRequest)wr;
                row[1] = ((AdShowWorkRequest)wr).getShowAd().getSumbid();
                row[2] = ((AdShowWorkRequest)wr).getShowEn();
                row[3] = ((AdShowWorkRequest)wr).getShowAd().getAd().getAd().getOwner();
                dtm.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adpay = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        alert = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(570, 440));

        adpay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Advertisement", "Sumbidding", "SSP", "Advertiser"
            }
        ));
        jScrollPane1.setViewportView(adpay);

        jButton1.setText("Send Pay Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        alert.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(alert)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(alert)
                .addGap(69, 69, 69)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = adpay.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select an Ad from the list first.");
            return;
        }
        
        //minus account of the enterprise
        AdShowWorkRequest adswr = (AdShowWorkRequest) adpay.getValueAt(selectedRow, 0);
        float payamount = adswr.getShowAd().getSumbid();
        enterprise.getFinancialAccount().makePayment(payamount);
        
        //send alert to SSP Financial dpt to receive the money
        AdPayWorkRequest adpwr = new AdPayWorkRequest(adswr.getShowAd());
        adpwr.setSender(userAccount);
        adpwr.setAdSender(enterprise);
        SSPEnterprise ssp = adswr.getShowEn();
        for(Organization ooo : ssp.getOrganizationDirectory().getOrganizationList()){
            if(ooo instanceof SSPFinancialOrganization){
                ooo.getWorkQueue().getWorkRequestList().add(adpwr);
                break;
            }
        }
        organization.getWorkQueue().getWorkRequestList().add(adpwr);
        userAccount.getWorkQueue().getWorkRequestList().add(adpwr);
        
        //send to advertiser to pay for the show
        ChargeAdvertiserWorkRequest cadwr = new ChargeAdvertiserWorkRequest();
        cadwr.setSaler(enterprise);
        cadwr.setShowAd(adswr.getShowAd());
        cadwr.setC(adswr.getC());
        cadwr.setSender(userAccount);
        cadwr.setShowPlace(adswr.getShowPlace());
       // if(adswr.getShowAd().getAd().getAd().getOwner().getOrganizationDirectory().getOrganizationList()==null){
         //   adswr.getShowAd().getAd().getAd().getOwner().getOrganizationDirectory().setOrganizationList(new ArrayList());
       // }
        for(Organization oooo : adswr.getShowAd().getAd().getAd().getOwner().getOrganizationDirectory().getOrganizationList()){
            if(oooo instanceof AdvertiserFinancialOrganization){
                oooo.getWorkQueue().getWorkRequestList().add(cadwr);
                break;
            }
        }
        organization.getWorkQueue().getWorkRequestList().add(cadwr);
        userAccount.getWorkQueue().getWorkRequestList().add(cadwr);
        alert.setText("Pay Request Send Sucessfully!");
        
        organization.getWorkQueue().getWorkRequestList().remove(adswr);
        populateTable();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adpay;
    private javax.swing.JLabel alert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
